//
//  LoginSceneViewController.swift
//  TesteiOSv2
//
//  Created by Vlad Lopes on 14/02/21.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginSceneDisplayLogic: class
{
    func displayUser(viewModel: LoginScene.ReadLogin.ViewModel)
    func displayMessage(viewModel: LoginScene.ValidateLogin.ViewModel)
    func routeToAccount(viewModel: SetClient.ViewModel)
}

class LoginSceneViewController: UIViewController, LoginSceneDisplayLogic
{
  var interactor: LoginSceneBusinessLogic?
  var router: (NSObjectProtocol & LoginSceneRoutingLogic & LoginSceneDataPassing)?

    
    @IBOutlet weak var txtLogin: UITextField!
    @IBOutlet weak var txtPassword: UITextField!
    @IBOutlet weak var lblAlert: UILabel!
    @IBOutlet weak var bttLogin: UIButton!
    
  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = LoginSceneInteractor()
    let presenter = LoginScenePresenter()
    let router = LoginSceneRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
    if bttLogin != nil {
        bttLogin.layer.cornerRadius = 8
    }
    
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
    
    func routeToAccount(segue: UIStoryboardSegue?) {
        
    }
  
  // MARK: View lifecycle
  
    override func viewDidLoad()
    {
        super.viewDidLoad()
        
        searchLogin()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        txtPassword.text = ""
    }
  
  // MARK: Searching for stored login
  
  //@IBOutlet weak var nameTextField: UITextField!
  
    func searchLogin()
    {
        let request = LoginScene.ReadLogin.Request()
        interactor?.readStoredLogin(request: request)
    }
  
    func displayUser(viewModel: LoginScene.ReadLogin.ViewModel)
    {
        txtLogin.text = viewModel.login
    }
    
    func displayMessage(viewModel: LoginScene.ValidateLogin.ViewModel)
    {
      lblAlert.text = viewModel.alertMessage
    }
    
    func routeToAccount(viewModel: SetClient.ViewModel) {
        DispatchQueue.main.async {
            self.performSegue(withIdentifier: "Account", sender: nil)
        }
        
    }
    
    @IBAction func buttonTapped(_ sender: Any) {

        let request = LoginScene.ValidateLogin.Request(login: txtLogin.text!,
                                                       password: txtPassword.text!)
        interactor?.validateLogin(request: request)
        
//        if txtLogin.text == "nova@tela.com" {
//            performSegue(withIdentifier: "AccountSegue", sender: nil)
//        }
    }
}




